
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package areatrapecio;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 4;
  public static final int COMA = 2;
  public static final int FINLINEA = 3;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "FINLINEA",
  "NUMERO"
  };
}

